afkcode/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('obscurity/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('blog/', include('blog.urls')),
    path('courses/', include('courses.urls')),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('', include('blog.urls')),
    path('__reload__/', include('django_browser_reload.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog import views

urlpatterns = [
    path('', views.blog_index, name='blog_index'),
    path('blog/page=<int:page>', views.blog_index, name='blog_index_paged'),
    path('blog/page=<int:page>&posts=<int:posts_per_page>', views.blog_index, name='blog_index_paged'),
    path('blog/<int:pk>-<slug:slug>', views.blog_detail, name='blog_detail'),
    path('blog/<int:year>/<int:month>/<int:pk>-<slug:slug>', views.blog_detail_with_date, name='blog_detail_with_date'),
    path('category/<category>/', views.blog_category, name='blog_category'),
]

courses/urls.py
from django.urls import path
from courses import views

urlpatterns = [
    path('', views.course_index, name='course_index'),
    path('school=<filter_by_school>', views.course_index, name='course_index'),
    path('<int:pk>-<slug:slug>', views.course_detail, name='course_detail')
]

courses/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class School(models.Model):
    name = models.CharField(max_length=60)
    initials = models.CharField(max_length=10)
    logo = models.ImageField(upload_to='school_logos/', null=True, blank=True)
    website = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=60)
    subject = models.CharField(max_length=10)
    code = models.CharField(max_length=5)
    units = models.PositiveSmallIntegerField()
    description = models.TextField(null=True, blank=True)
    school = models.ForeignKey('School', on_delete=models.PROTECT)
    categories = models.ManyToManyField('blog.Category', blank=True)
    slug = models.SlugField(default='', editable=False, max_length=25, null=False)

    class Status(models.IntegerChoices):
        PLANNED = 1
        IN_PROGRESS = 2
        COMPLETED = 3
    status = models.IntegerField(choices=Status.choices, default=Status.PLANNED)

    class Semester(models.IntegerChoices):
        SPRING_A = 1
        SPRING_B = 2
        SUMMER_A = 3
        SUMMER_B = 4
        FALL_A = 5
        FALL_B = 6
    semester = models.IntegerField(choices=Semester.choices, blank=True, null=True)
    year = models.PositiveSmallIntegerField(blank=True, null=True)

    def __str__(self):
        return f'{self.school.initials}: {self.subject}{self.code} - {self.name}'

    def get_absolute_url(self):
        kwargs = {
            'pk': self.pk,
            'slug': self.slug
        }
        return reverse('course_detail', kwargs=kwargs)

    def save(self, *args, **kwargs):
        value = f'{self.school.initials}-{self.subject}{self.code}'
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)


class Credential(models.Model):
    major = models.CharField(max_length=60)
    type = models.CharField(max_length=60)
    type_letters = models.CharField(max_length=5, null=True, blank=True)
    school = models.ForeignKey('School', related_name='credentials', on_delete=models.PROTECT)

    def __str__(self):
        if self.type_letters is None:
            prefix = self.type
        else:
            prefix = self.type_letters
        return f'{prefix} in {self.major} from {self.school.initials}'

courses/views.py
from django.shortcuts import render
from courses.models import Course, School
from projects.models import Project


def course_index(request, filter_by_school=''):
    if filter_by_school:
        all_courses = Course.objects.filter(school__initials=filter_by_school.upper())
    else:
        all_courses = Course.objects.all().order_by('school__name')
    courses_in_progress = all_courses.filter(status=Course.Status.IN_PROGRESS).order_by('subject', 'code')
    courses_completed = all_courses.filter(status=Course.Status.COMPLETED).order_by('year', 'semester')
    courses_planned = all_courses.filter(status=Course.Status.PLANNED).order_by('year', 'semester')

    school_list = School.objects.values('name', 'initials').order_by('name')

    context = {
        'courses_in_progress': courses_in_progress,
        'courses_completed': courses_completed,
        'courses_planned': courses_planned,
        'filter_by_school': filter_by_school,
        'school_list': school_list
    }
    return render(request, 'course_index.html', context)


def course_detail(request, slug, pk):
    course = Course.objects.get(pk=pk)
    projects = Project.objects.filter(course=course)
    context = {
        'course': course,
        'projects': projects
    }
    return render(request, 'course_detail.html', context)

courses/templates/_course_index_card.html
<div class="row gx-3 gy-2 mt-0 mb-3">
    <h1 class="h2 pb-2 my-0">{{ section_title }}</h1>
    {% for course in courses %}
    <div class="col-md-6 col-lg-4 col-xxl-3">
        <div class="card mb-2 shadow-sm">
            <div class="card-body">
                <h2 class="h5 card-title">{{ course.subject }} {{ course.code }}</h2>
                <p class="card-subtitle mb-2">{{ course.name }}</p>
                <p class="card-text text-muted">{{ course.get_semester_display }} {{ course.year }}</p>
                <a role="button" href="{% url 'course_detail' pk=course.pk slug=course.slug %}" class="btn btn-primary bg-gradient">
                    Read More
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

courses/templates/course_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}afkcode.com - {{ course.subject }} {{ course.code }}: {{ course.name }}{% endblock title %}

{% block nav %}{% with active_section='courses' %}{{ block.super }}{% endwith %}{% endblock %}

{% block content %}
    <div class="col-md-9 offset-md-1 mt-3">
        <div class="card p-4 shadow">
            <div class="row g-0">
                <div class="col-sm-3">
                    <img class="w-100"
                            src="{% get_media_prefix %}{{ course.school.logo }}"
                            alt="{{ course.school.initials }} logo">
                </div>
                <div class="col mx-3">
                    <div class="card-title">
                        <h1>{{ course.subject }} {{ course.code }}: {{ course.name }}</h1>
                    </div>
                    <div class="card-subtitle">
                        <div class="card-text">{{ course.school }}</div>

                        <div class="card-text float-start me-3">{{ course.units }} units</div>

                        {% include '_category_list.html' with categories=course.categories.all description=course.name %}

                        <div id="semester" class="card-text">
                            {% if course.get_status_display == 'Completed' %}
                                <span class="badge bg-gradient bg-success">Completed</span>
                            {% elif course.get_status_display == 'In Progress' %}
                                <span class="badge bg-gradient bg-info">In Progress</span>
                            {% else %}
                                Planned for
                            {% endif %}
                            {{ course.get_semester_display }} {{ course.year }}
                        </div>

                    </div>

                </div>
            </div>
            <div class="row g-0 card-body">
                <div class="card-text mb-3">
                    {{ course.description | linebreaks }}
                </div>
            </div>

            {% if projects %}
                <div class="row mx-2">
                    <h2>Associated projects:</h2>
                    <ul id="projects" class="list-group-flush">
                        {% for project in projects %}
                            <li class="list-group-item">
                                <a href="{% url 'project_detail' project.pk project.slug %}">{{ project.title }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

        </div>
    </div>
{% endblock content %}

courses/templates/course_index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    afkcode.com - {% if filter_by_school %}{{ filter_by_school }} {% endif %}Courses
{% endblock title %}

{% block nav %}{% with active_section='courses' %}{{ block.super }}{% endwith %}{% endblock %}

{% block content %}
    <div class="row sticky-top bg-light mb-3 py-2">
        <div class="dropdown mx-0 px-2">
            <button class="btn btn-sm btn-secondary gradient dropdown-toggle mx-0" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                Filter by school
            </button>
            <span class="ms-3">
                Current:
                {% if filter_by_school %}
                    {{ filter_by_school }}
                {% else %}
                    All schools
                {% endif %}
            </span>
            <ul class="dropdown-menu shadow" aria-labelledby="dropdownMenuButton1">
                <li><a class="dropdown-item" href="{% url 'course_index' %}">Clear filter</a></li>
                <li><hr class="dropdown-divider"></li>
                {% for school in school_list %}
                    <li><a class="dropdown-item" href="school={{ school.initials }}">{{ school.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="row">
        {% if not courses_in_progress and not courses_completed and not courses_planned %}
            <span class="mx-1">No courses found for current filter. Try selecting another school.</span>
        {% else %}
            {% if courses_in_progress %}
                {% include '_course_index_card.html' with courses=courses_in_progress section_title='In Progress' %}
            {% endif %}
            {% if courses_completed %}
                {% include '_course_index_card.html' with courses=courses_completed section_title='Completed' %}
            {% endif %}
            {% if courses_planned %}
                {% include '_course_index_card.html' with courses=courses_planned section_title='Planned' %}
            {% endif %}
        {% endif %}

    </div>
{% endblock content %}